global:
  domain: digit.local.quickstart
cluster-configs:
  namespaces:
    create: create
    values: [ monitoring, jenkins ]
  root-ingress:
    namespace: jenkins
    serviceName: jenkins
    servicePort: 8080
    appRoot: ""
    cert-issuer: "letsencrypt-prod"
    
  git-sync:
    namespace: monitoring  

jenkins:
  persistence:
    enabled: true
    size: "251Gi"
    #aws:
     # - volumeId: "vol-0ceabde5ed7c9e6c4"
      #  zone: ap-south-1b
  oauth:
    enabled: false
    acl:
      admin:
        - admin
      user:
        - microservicedev
        - ukduat
        - biharuat
        
  jobBuilder:
    repos: >-
      'git@github.com:HCM-MOZ-IMPEL/DIGIT-Dev-Moz-Impl.git','git@github.com:egovernments/core-services.git','git@github.com:egovernments/business-services.git','git@github.com:egovernments/municipal-services.git','git@github.com:egovernments/utilities.git','git@github.com:egovernments/frontend.git','git@github.com:egovernments/DIGIT-Dev.git', 'git@github.com:egovernments/eGov-Punjab-Implementation.git', 'git@github.com:egovernments/covid-backend.git','git@github.com:egovernments/requester-dashboard.git','git@github.com:egovernments/approver-dashboard.git','git@github.com:eNagarsewaU/ukd-rainmaker-customization.git','git@github.com:egovernments/punjab-rainmaker-customization.git', 'git@github.com:egovernments/egov-coexistence.git','git@github.com:egovernments/eGov-UP-Implementation.git', 'git@github.com:egovernments/test-automation.git', 'git@github.com:egovernments/CoronaSafe.git', 'git@github.com:egovernments/eGov-dcr-service.git', 'git@github.com:eNagarsewaU/DIGIT-UKD.git', 'git@github.com:egovernments/digit-ui.git', 'git@github.com:egovernments/DIGIT-Works.git', 'git@github.com:egovernments/health-campaign-services.git','git@github.com:egovernments/punjab-mgramseva.git','git@github.com:egovernments/SANITATION.git','git@github.com:egovernments/Digit-Core.git','git@github.com:egovernments/iFix-Dev.git','git@github.com:egovernments/bihar-mgramseva.git','git@github.com:egovernments/HCM-Mozambique-Implementation.git','git@github.com:odisha-muktasoft/mukta-customization.git','git@github.com:odisha-muktasoft/MUKTA_IMPL.git','git@github.com:pmidc-digit/DIGIT-PUNJAB.git','git@github.com:egovernments/DIGIT-Frontend.git','git@github.com:egovernments/DIGIT-UI-LIBRARIES.git','git@github.com:egovernments/Program-Management-Services.git','git@github.com:egovernments/unified-benefits-administration.git','git@github.com:egovernments/DIGIT-Common.git','git@github.com:egovernments/DIGIT-Analytics.git','git@github.com:egovernments/URBAN.git'
  deploymentJobs:
    
    - name: bihar-uat
      acl: [biharuat]
    - name: uat
      acl: [microservicedev] 
    - name: ukd-dev
      acl: [egovernments*ukd-dev] 
    - name: ukd-sdc-uat
      acl: [ukduat]                 
    - name: ci
      acl: [admin]      

  deployjobBuilder:
    repo: >-
      'git@github.com:egovernments/DIGIT-DevOps.git' 

   
  master:
    ingress:
      enabled: true
    resources:
      limits:
        cpu: "2500m"
        memory: "5120Mi"
    javaOpts: "-Xms3100M -Xmx3100M -Duser.timezone=Asia/Calcutta"

nginx-ingress:
  replicas: 1
  default-backend-service: "jenkins/jenkins"
  namespace: jenkins
  cert-issuer: "letsencrypt-staging"
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-ciphers: "EECDH+CHACHA20:EECDH+AES"
  ssl-ecdh-curve: "X25519:prime256v1:secp521r1:secp384r1"
  controller:
    image:
      repository: egovio/nginx-ingress-controller
      tag: "0.26.1"

cert-manager:
  namespace: jenkins
  email: "pramodk935@gmail.com"

cluster-autoscaler:
  namespace: jenkins
  #cloudProvider: aws  
  #awsRegion: ap-south-1
  #autoDiscovery:
    clusterName: egov-cicd
    tags:
    - kubernetes.io/cluster/egov-cicd

postgres:
  namespace: jenkins
  postgresDatabase: ci_database

grafana: 
  image:
    repository: grafana/grafana
    tag: 9.0.0

  initContainers:
    gitSync:
      enabled: true
      repo: "git@github.com:egovernments/monitoring"
      branch: "master"

  ingress:
    hostName: monitoring.digit.org 
    context: ""
    additionalAnnotations: | 

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s"
      serve_from_sub_path: true 

  env: |
    - name: GF_SERVER_DOMAIN
      value: {{ .Values.ingress.hostName | quote }}    

  datasources: 
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: DIGIT-Dev
        type: prometheus
        url: https://prometheus-dev.digit.org
        isDefault: false 
      - name: DIGIT-QA
        type: prometheus
        url: https://prometheus-qa.digit.org
        isDefault: false
      - name: DIGIT-UAT
        type: prometheus
        url: https://prometheus-uat.digit.org
        isDefault: false
      - name: DIGIT-Staging
        type: prometheus
        url: https://prometheus-staging.digit.org
        isDefault: false
    
     


       
